### PR TITLE
Update intake catalog

### PR DESCRIPTION
**Pull request by ellesmith88**
Updated to latest list of datasets, excluding datasets with errors.

Error output included:
[errors.txt](https://github.com/cp4cds/c3s_34g_manifests/files/6514783/errors.txt)

Also excluded these datasets 
c3s-cmip6.ScenarioMIP.THU.CIESM.ssp585.r1i1p1f1.Amon.rsus.gr.v20200806
c3s-cmip6.ScenarioMIP.THU.CIESM.ssp585.r1i1p1f1.Amon.rsdt.gr.v20200806
c3s-cmip6.ScenarioMIP.THU.CIESM.ssp585.r1i1p1f1.Amon.rlus.gr.v20200806

As their time ranges were from 4029 to 4114.

### CODE REVIEW

**Comment by agstephens** [comment]
@ellesmith88 this looks good. Please merge and let me know when it's done.

**Comment by cehbrecht** [comment]
@ellesmith88 @agstephens do we want to merge and use this catalog? Or the demo one:
https://github.com/cp4cds/c3s_34g_manifests/blob/master/intake/demos/c3s.yml

**Comment by ellesmith88** [comment]
@cehbrecht If we merge this at the moment, it will break the production service I think - because the fix mentioned in https://github.com/roocs/34e-mngmt/issues/95 is needed for this catalog.

**Comment by cehbrecht** [comment]
@ellesmith88 ok ... to be save we can merge after the successful update of the rook service. But I will use for the update the catalog from this PR:
```
[catalog]
#intake_catalog_url = https://raw.githubusercontent.com/cp4cds/c3s_34g_manifests/master/intake/catalogs/c3s.yaml
intake_catalog_url = https://raw.githubusercontent.com/cp4cds/c3s_34g_manifests/update_intake_catalog/intake/catalogs/c3s.yaml
```

**Comment by ellesmith88** [comment]
@cehbrecht ok 👍  I'll make sure not to delete/ change this branch

**Pull request merged**
