### PR TITLE
added intake catalog for c3s-cmip6

### PR DESCRIPTION
**Pull request by cehbrecht**
This PR adds an intake catalog for the c3s-cmip6 inventory. It is generated from the yaml inventory file:
```
./inventories/c3s-cmip6/c3s-cmip6_files_latest.yml
```

This PR includes a `catalog_builder.py` to build the intake catalog. See the Readme on how to use the builder.

See this notebook on how to use the catalog:
https://nbviewer.jupyter.org/github/roocs/rooki/blob/master/notebooks/demo/demo-intake-catalog.ipynb

Motivation: the yaml inventory used by rook is breaking sometimes when parallel requests are coming in. Also we may want to use intake catalogs to share with c3s ... in the future.

### CODE REVIEW

**Comment by cehbrecht** [comment]
@agstephens @ellesmith88 Please have a look at it :)

**Comment by ellesmith88** [comment]
@cehbrecht looks good to me!

**Comment by cehbrecht** [comment]
@agstephens can we merge it to have the catalog in place? It does not interfere with the inventory.

**Comment by agstephens** [comment]
@cehbrecht looks good!

**Pull request merged**
